[features]
seeds = false
[programs.localnet]
b_nonymous = "8TPAjcQxNyMQF52RPPyeJuQ48zot9RGDKRZT15cQC2h4"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/william/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
